### PR TITLE
Auto-complete suggestor implementation

### PR DESCRIPTION
**Pull request by Soptq**
This PR tries to solve the #29 task: improve auto-complete suggestor.

Major changes:
* Attribute `parent` added to the type `command` to indicate each command's previous stage. https://github.com/Soptq/smrepl/blob/fc69336dd63b2771f2d84c1eafabc80e361fab6d/repl/repl.go#27
* commands' name changed. for example `wallet-info` changed to `wallet info`. https://github.com/Soptq/smrepl/blob/fc69336dd63b2771f2d84c1eafabc80e361fab6d/repl/repl.go#114

### CODE REVIEW

**Review by avive — COMMENTED** [review]
Thanks for this nice PR! I will review it soon and will share comments here.

**Comment by avive** [comment]
I've reviewed the PR - the suggestor changes are good but all commands seems to be broken. 
Try `status node`, `state glboal`, etc...
To test this you want to run a local node on a spacemesh devnet.
To do so, get the node from this release: https://github.com/spacemeshos/go-spacemesh/releases/tag/untagged-ec134df89a3c250755af
And download this config file to use with it: https://storage.googleapis.com/spacecraft-data/mininet-archive/config.json

Start it with `./go-spacemesh -c config.json` and start smrepl - it should auto connect to your locally running devnet node.

**Comment by Soptq** [comment]
I see, really appreciate your reviewing. I have fixed the issues in my latest commit.

Changes:
1. Fix executor does not execute
2. use automaton to parse, now it should support multi-stage commands (previously it will only support two-stage command)
3. remove `invalid` function, replace it with `nil` which is more understandable for me.

All commands are now tested, it should be working now.

**Comment by Soptq** [comment]
Any problems, possible improvements or suggestions are appreciated. Thanks for your time.

**Comment by avive** [comment]
LGTM

**Pull request merged**
