### PR TITLE
Smesher api implementation

### PR DESCRIPTION
**Pull request by avive**
Please don't merge yet - WIP

### CODE REVIEW

**Comment by avive** [comment]
Trying to subscribe to the PostDataCreationProgress stream from a client results in this error:

$ pos-stream-progress
<APP> ERRO 002 13:53:42.368 repl.printPostDataCreationProgress ▶ error reading from post data creation stream: rpc error: code = FailedPrecondition desc = no post data creation session is in progress

Looks like node returns this wrongly. Clients should be able to subscribe to this stream at any time, including before starting to create pos data and node should not return an error on that stream - it should only return pos progress messages on it.

**Comment by moshababo** [comment]
> Looks like node returns this wrongly. Clients should be able to subscribe to this stream at any time, including before starting to create pos data and node should not return an error on that stream - it should only return pos progress messages on it.

As discussed, this protection was removed in the latest implementation. The stream now hangs until session starts.

**Comment by moshababo** [comment]
https://github.com/spacemeshos/cli-wallet/pull/23/commits/c3d85d555de91643f26ec4e703b2d844588ab7e1 changes:

* `/common/storage.go`: `os.WriteFile` / `os.ReadFile` -> `ioutil.WriteFile` / `ioutil.ReadFile`. 
   I’m not sure how it previously passed compilation.
* Support https://github.com/spacemeshos/api/pull/145/commits/81ae866b03421ab87688ed268d61f8bea99691bf changes, specified here: https://github.com/spacemeshos/api/pull/145#issuecomment-855253781
* In `printPostStatus`, remove the reliance on the `"pos-data.json"` file. The returned status now returns this data, so clients won't need to maintain it for this purpose.

**Comment by moshababo** [comment]
Implementation update is still pending. Will publish the relevant commit once pushed.

**Comment by avive** [comment]
There are 2 issues after the latest commits when running against go-spacemesh from smesher-api branch and api from smesher-api branch: Status after setting up post returns error - missing data dir. 
```
$ post status
⚠️  Proof of spacetime data creation error: metadata file is missing
Proof of spacetime configuration:
  Data dir (relative to node or absolute): .
  Date files: 1
  Compute provider id: 0
  Throttle when computer is busy: false
  Bits per label: 8
  Units: 1
  Labels: 1024
  Size (GiB): 9.536743e-07
  Size (Bytes): 1024
```

**Comment by moshababo** [comment]
> When running against go-sm from smesher-api branch and api from smesher-api branch: api response reports a missing meta-data file error:

This happens due to a recent incompatible update in the metadata file name.. if you'll provide a fresh datadir or delete the post data files in the current one, it should work. Otherwise LMK.

**Comment by avive** [comment]
> This happens due to a recent incompatible update in the metadata file name.. if you'll provide a fresh datadir or delete the post data files in the current one, it should work. Otherwise LMK.

Thanks for the info. I will delete old metadata files and try again.

**Comment by avive** [comment]
@moshababo - do you want to finish with this PR now that the api changes have been merged or would you like me to do this?

**Comment by moshababo** [comment]
> @moshababo - do you want to finish with this PR now that the api changes have been merged or would you like me to do this?

Plz go ahead and finish it.

**Comment by avive** [comment]
@moshababo - this PR is ready for review

**Pull request merged**
